name: "SML/NJ Bug Report Form"
description: "Submit a bug report"
title: "[Bug]: <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        # Instructions

        Please use this form to report problems in the **legacy** version of
        [**Standard ML of New Jersey**](https://smlnj.org).

        To request a feature, please use the
        [feature-request form](https://github.com/smlnj/bug-form-test/issues/new?template=feature_request).

        Before creating a new bug report, please search the
        [open issues](https://github.com/smlnj/bug-form-test/issues) to see if your
        problem has already been reported (if so, please add your information to the existing
        issue).
  - type: markdown
    attributes:
      value: >
        # System Information

        Please provide information about your system
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of SML/NJ are you using?
      options:
        - "110.99"
        - "110.99.1"
        - "110.99.2"
        - "110.99.3 (Latest)"
    validations:
      required: true
  - type: checkboxes
    id: operating_system
    attributes:
      label: What operating system(s) exhibit the bug?
      description: You may specify more than one.
      options:
        - label: Linux
        - label: macOS
        - label: Windows
        - label: "Other Unix"
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: What OS version?
      description: |
        Additonal information about the OS; *e.g.*, "Windows 10" or "macOS Monterey."
  - type: checkboxes
    id: architecture
    attributes:
      label: What processor exhibits the bug?
      description: You may specify more than one.
      options:
        - label: "Arm (using Rosetta)"
        - label: "PowerPC"
        - label: "Sparc"
        - label: "x86 (32-bit)"
        - label: "x86-64 (64-bit)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        # The Problem

        Please provide information about the problem.
  - type: dropdown
    attributes:
      label: Component
      description: Which component of the system is affected by the bug?
      options:
        - Installation
        - Core system
        - Compilation manager (CM)
        - Basis Library
        - SML/NJ Library
        - Command-line tool (*e.g.*, ml-antlr, ml-yacc, *etc.*)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Severity
      options:
        - Cosmetic
        - Minor
        - Major
        - Critical
    validations:
      required: true
  - type : textarea
    id: description
    attributes:
      label: Description of the problem
      description: Provide a short description of what the problem is.
    validations:
      required: true
  - type : textarea
    id: transcript
    attributes:
      label: Transcript
      description: Please include a transcript of the bad behavior here.
  - type : textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
  - type : textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: >
        Explain how to reproduce the problem.  Include sample code (the smaller, the
        better) that exhibits the problem, when ppropriate.  If reproducing the bug
        requires a large system, then please provide a download link for getting the
        code that exhibits the bug.
    validations:
      required: true
  - type : markdown
    attributes:
      value: >
        # Additional Information
  - type : textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: >
        Please provide any additional information that may help us diagnose and fix
        the problem.
  - type: input
    id: email
    attributes:
      label: Email address
      description: >
        Please provide an email address to allow us to contact you
        if we require additional information.
    validations:
      required: true
