name: "SML/NJ Feature Request Form"
description: "Suggest an idea for a new feature for SML/NJ"
title: "<title>"
labels: ["enhancement"]
body:
  - type: markdown
      description: >
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is.

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you
        have considered.

        **Additional context**
        Add any other context about the feature request here.
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
      description: >
        Please provide any additional information that may help us diagnose and fix
        the problem.
